### ISSUE TITLE
Singularity splicekit is not working

### ISSUE THREAD

**Issue by marina-yurieva** [bedapub/splicekit#1]
I'm running `singularity run splicekit.sif splicekit process` and it outputs `splicekit process` and quits without giving errors or producing any result. I have splicekit.config and samples.tab files in the same directory. 

Would appreciate your help!

**Comment by grexor** [comment]
Hi Marina, sorry for the misunderstanding, I will also update the docs:

* you still need to install splicekit (best via `pip install splicekit`)
* you can then use the singularity container (all other software dependencies are there, like STAR, edgeR etc.)

You would need to update the `splicekit.config` file like this:

```
container="singularity run splicekit.sif"
```

(replace the path to the `splicekit.sif` file to accommodate your setup)

Hope this helps,
Cheers,
Gregor
