### ISSUE TITLE
Tab characters required for the samples.tab file

### ISSUE THREAD

**Issue by Amit-H** [bedapub/splicekit#27]
Issue with VScode as it does not enter tab characters by default, it adds 4 spaces (default) which causes the tool to break. Should add faq section to include this caveat.

**Comment by grexor** [comment]
Thanks Amit for trying it out! I updated the [docs](https://docs.google.com/document/d/15ZRCeK8xyg3klLktZSHZ9k__Xw_BZRn_Q-J4W35JNnQ/edit?usp=sharing) and also added a comment to the first line of the provided [samples.tab](https://github.com/bedapub/splicekit/blob/dev/datasets/GSE126543/samples.tab) files...hope this helps.
