### ISSUE TITLE
featureCounts

### ISSUE THREAD

**Issue by grexor** [bedapub/splicekit#30]
To be used from the container if specified (exons, genes), check

**Comment by santataRU** [comment]
Hi Gregor,

In splicekit, are counts for all features (splice junctions, exons, genes, etc.) obtained using `featureCounts` from the [Rsubread package](https://subread.sourceforge.net/featureCounts.html)?

Best,
Xiao

**Comment by grexor** [comment]
- junctions: counted by [junctions.py](https://github.com/bedapub/splicekit/blob/main/splicekit/core/junctions.py)
- exons, genes, anchors: featureCounts
